### PR TITLE
Refactoring and improving propagation stopping functionality

### LINKED ISSUE #3: Add Tests
The next release must have tests, covering at least 100% of the API.

### LINKED ISSUE #5: Needs Uniform Handling
Handlers hooked with `EventManager#attach()` must all receive 1 parameter: the `Event` object.

### LINKED ISSUE #6: Bring up to Dhii Standard
The code needs to be brought up to Dhii standard. This includes, but is not limited to:

* Adding proper class, method and property docs
* Adding `since` tags to docs, where appropriate
* Fixing naming scheme for properies and methods
* Fixing code standards

### LINKED ISSUE #11: Make Propagation Compatible With Native Handlers
## The Symptom

The wrapped handlers are capable of detecting when an `EventInterface` stops propagation via `isPropagationStopped()`. Native handlers, however, have no such check; neither are they capable of implementing one since they do not even receive the event instance as argument.

This makes it impossible for a wrapped handler to be certain that no other handler will be executed for that event when there are native handlers that have yet to be executed.

## Recommended Solution

And most probably the _only_ solution.

A special handler can be attached to the `"all"` hook, making it trigger on all hooks. This handler can then create a wrapper for all native handlers. The wrapper handler already checks for propagation and halting if necessary, therefore solving the problem.

This should probably be an opt-in feature. Perhaps a `wrapWordPressHandlers()` method can be added to the manager that registers the special handler on the `all` hook.

### LINKED ISSUE #12: Improve Clear-Cache Handler
## The Problem

As I've mentioned in this [comment][1] for issue #11, the clear cache mechanism is too expensive. Here's why:

* A hook `some_hook` is triggered
* A wrapper handler is invoked
* The wrapper handler will get the cached event
* If the event is not cached, it is created and cached, and a clear cache handler is hooked on `some_hook` with priority `PHP_INT_MAX`

WordPress allows hook handlers to attach more handlers on the hook currently being "triggered". However, this triggers [`WP_Hook#resort_active_iterations()`][2], which re-sorts the handlers mid-iteration to maintain order by priority and is expensive in its own right.

## Recommended Solution

Attach the clear cache handler on the `all` hook. The `all` hook is triggered _before_ any hook. Handlers attached to `all` receive two arguments: the name of the hook that was triggered and the arguments given to it. The clear cache handler will simply remove the cached event instance that is mapped to the given hook name.

[1]: https://github.com/Dhii/wp-events/issues/11#issuecomment-283310945
[2]: https://core.trac.wordpress.org/browser/tags/4.7/src/wp-includes/class-wp-hook.php#L93

### PR DESCRIPTION
**Pull request by mecha**
Resolves #3
Resolves #5
Resolves #6
Fixes #11
Resolves #12
Makes #13 obsolete

----

## Details

The event manager in this PR keeps a cache of `EventInterface` instances. Since the events are triggered by WordPress and not by the event manager, the handlers cannot be directly given the event instances. Instead, they are wrapped in a callback that retrieves the event from the cache.

A bit of information regarding the WordPress event system. When an action or filter is triggered, WordPress first triggers the `all` hook. Handlers attached to `all` receive the name of the action/filter that was triggered. After all handlers attached to `all` are invoked, a `WP_Hook` instance that corresponds to the triggered hook is retrieved and its `apply_filters` method is called. This is the method that contains the code that calls the handler callbacks.

The event manager hooks 2 handlers onto `all`. The first clears any previously cached `EventInterface` instances, so that different chains of triggered events do not share the same event instance.

The second handler is used to replace the `WP_Hook` instances with instances of a replacement class, `WpHookReplacement`. This class redirects all method calls to the original `WP_Hook` instance, except for `apply_filters`. The replacement class implements `apply_filters` to wrap a `try..catch` block around the original `WP_Hook::apply_filters()` method that catches `StoppedPropagationExceptionInterface` exceptions to stop further handlers from being called. These exceptions are thrown by the wrapper handlers.

### CODE REVIEW

**Comment by mecha** [comment]
@XedinUnknown I used `10up/wp-mock` for testing, which requires a minimum of PHP `5.6` - therefore the builds for `5.4` and `5.5` fail during composer installation. Any advice?

**Comment by XedinUnknown** [comment]
Apparently, this package requires PHP 5.6+. How so?

**Comment by mecha** [comment]
🤣 Can you not read the comment just above your own? haha

**Comment by XedinUnknown** [comment]
Sorry, just wanted to note this not to forget later. How about this?
https://github.com/10up/wp_mock/blob/0.1.1/composer.json#L6

**Comment by mecha** [comment]
That'll work! Tests will need to undergo some changes though. Some of the used API is not present here. Looks like a minor job though, so that's good.

**Comment by mecha** [comment]
~Build is breaking in 7.1+ due to dev dependencies~

Build for PHP 7.1+ fixed in e3fdfa7

**Review by XedinUnknown — APPROVED** [review]

**Pull request merged**
