### PR TITLE
Improves Event Cache Clearing

### PR DESCRIPTION
**Pull request by mecha**
Attempts to incorporate a solution for #12 

----

This new mechanism registers only a single handle registered on the WordPress `all` hook, which is invoked before any handlers for any hook trigger. The handler receives the name of the triggered hook as parameter and uses that to clear any event instance from cache that might have been created during a prior invocation of that hook.

### CODE REVIEW

**Comment by XedinUnknown** [comment]
@mecha, I think this kind of change, and in general the event manager's main functionality itself, can have hidden issues that cannot be tested for using WP Mock, and therefore deserve a test in a real WP environment. Have you tried this code in such an environment? What about before these changes? What did you conclude?

**Comment by mecha** [comment]
@XedinUnknown Yes I tested on a pre-existing local WordPress environment with around 15 activated plugins, which should provide a sufficient number of actions and filters. This is what I also used to identify the problem when I reported issue #12.

My testing revealed that it is *much* faster; not inherently but relative to the previous mechanism which was incredibly slow. This meant that some pages, mostly on the admin side would time out. It also meant that we simply could not have added any more load to the event manager, making #11 impossible to implement. With this new mechanism, I've experienced vanilla performance.

Furthermore, purely from a technical point of view, I think we can agree that attaching a single persistent handler on `all` is easier to maintain than multiple handlers attached to their respective hooks.

**Comment by XedinUnknown** [comment]
@mecha, that's very interesting. ~There shouldn't be that much of an increase in load times. How many hooks did you add? WordPress handles hundreds of actions. Just 20-40 more wouldn't make such a big difference, IMHO~. From your explanation in #11 I understood that it's mostly due to WP's re-sorting of handlers. I'm still not sure why it's making such a big impact, since it's only double the amount of handlers being attached. Also, not sure why looking up wrapper cache is so expensive.

Can you explain in more detail how you tested?

**Comment by mecha** [comment]
@XedinUnknown The cache lookup is not the problem in itself, but it _does_ contribute because of the way I was forced to implement things - I will elaborate below. The problem is also not the WordPress re-sorting of handlers. This happens naturally in WordPress sometimes when hooks add/remove handlers to the currently triggered hook.

The problem is the WordPress re-sorting of handlers **on every hook**. Additionally, my recent testing also revealed that the re-sort happens **twice** for every hook. In a bit more detail:

Whenever a hook `x` is triggered, the `all` hook is also triggered prior to executing the handlers for `x`. Our handler on the `all` hook will attach a cache-clearing handler to `x` at max priority. This triggers the first re-sort since `x` is already considered to be executing, and we've just modified its handlers.

The solution for #11 requires us to wrap native-style handlers. These will be modified at this point in time. Following that, our max priority cache-clearing handler will execute, clearing the cached event instance and detach itself. Once again, `x` is still considered to be executing and we've just modified its handlers. This triggers the second re-sort.

The process outlined above is repeated for every single hook triggered in WordPress for that page's request. I hope you can visualize just how cumbersome that is 😆 

----

Testing was pretty trivial. My WordPress pages were timing out after enabling the initial solution for wrapping native handlers, so identification of the problem was automatic.

I logged all the hooks being executed to a file and identified that WordPress was timing out before reaching the end of its execution. I had a handler attached relatively close to the end of execution (admin footer text) and it wasn't being invoked. Disabling the wrapping of native handlers stopped the timing out.

With some additional logging inside of `WP_Hook` I discovered that the re-sort was being triggered as explained above. The conclusion then became obvious.

It is worth mentioning that if we do not consider the wrapping of native handlers (the solution for #11), then this change to the cache clearing mechanism has seemingly no affect. But if such wrapping were to affect every WordPress hook and handler, the effect multiplies to absurdity.

With these changes, only a single persistent handler is required - one that is universal for all hooks and handlers in WordPress - attached to `all` **once**. It will manage the cached event instance by deleting it before any handlers are invoked for the triggered hook, thus ensuring that the chain of handlers about to be triggered will receive a fresh new event instance. This bypasses the re-sort altogether and allows us to implement a solution for #11 with negligible performance impact, as I [described here](https://github.com/Dhii/wp-events/issues/11#issuecomment-283310945).

**Comment by mecha** [comment]
The solution in this PR has been incorporated into, and improved upon, in PR #14

**Pull request merged**
